[profile.default]
src = "contracts"
test = "foundry-test"
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.24"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
remappings = ["@openzeppelin/=node_modules/@openzeppelin/"]
